(() => {
  const events = [];
  const stories = {};
  const register = (entries) => {
    entries.forEach((entry) => {
      const { stories: entryStories, ...event } = entry;
      events.push(event);
      stories[event.id] = entryStories;
    });
  };

  register([
    { id: "hong-gildong-1", persona: "hong-gildong", title: "활빈당의 밤배달", description: "이웃에게 비밀 도움 요청이 왔다.", category: "community", tags: ["choice"], choices: [{ text: "몰래 돕는다", effects: { reputation: 1, money: -1 }, personaWeight: 2 }, { text: "제도 개선 제안", effects: { growth: 1, reputation: 1, money: -1 }, personaWeight: 0 }], stories: ["쪽문에 보따리를 두고 사라졌다.", "절차가 느렸지만 길이 열렸다."] },
    { id: "hong-gildong-2", persona: "hong-gildong", title: "가면의 소문", description: "정체를 아는 사람이 나타났다.", category: "community", tags: ["fate"], choices: [{ text: "조용히 넘긴다", effects: { reputation: 1, happiness: 1 }, personaWeight: 2 }, { text: "스스로 밝힌다", effects: { reputation: 2, happiness: -1 }, personaWeight: 0 }], stories: ["미스터리한 영웅으로 남았다.", "칭찬은 컸지만 부담도 늘었다."] },
    { id: "hong-gildong-3", persona: "hong-gildong", title: "활빈당의 규칙", description: "동료가 규칙을 어겼다.", category: "growth", tags: ["relationship"], choices: [{ text: "원칙을 지킨다", effects: { reputation: 1, growth: 1, happiness: -1 }, personaWeight: 2 }, { text: "한 번 눈감기", effects: { happiness: 1, reputation: -1 }, personaWeight: 0 }], stories: ["원칙이 신뢰를 지켰다.", "관계는 유지했지만 찜찜했다."] },
    { id: "simcheong-1", persona: "simcheong", title: "효심의 선택", description: "가족이 큰 지출을 필요로 한다.", category: "family", tags: ["choice"], choices: [{ text: "내가 감당", effects: { money: -2, happiness: 1, reputation: 1 }, personaWeight: 2 }, { text: "함께 분담", effects: { growth: 1, happiness: 1, money: -1 }, personaWeight: 0 }], stories: ["가족의 미소가 돌아왔다.", "함께 나누니 마음이 가벼웠다."] },
    { id: "simcheong-2", persona: "simcheong", title: "용궁의 기회", description: "뜻밖의 보상이 약속되었다.", category: "luck", tags: ["fate"], choices: [{ text: "기회를 잡는다", effects: { money: 2, happiness: 1 }, personaWeight: 2 }, { text: "가족 곁에 남음", effects: { happiness: 2, reputation: 1 }, personaWeight: 0 }], stories: ["행운이 손에 들어왔다.", "곁을 지켜 마음이 따뜻했다."] },
    { id: "simcheong-3", persona: "simcheong", title: "눈 뜨는 마음", description: "희생의 사실이 알려졌다.", category: "family", tags: ["relationship"], choices: [{ text: "담담히 말한다", effects: { reputation: 1, happiness: 1 }, personaWeight: 2 }, { text: "조용히 넘긴다", effects: { growth: 1, happiness: 1 }, personaWeight: 0 }], stories: ["고백이 서로를 가깝게 했다.", "말 없이도 마음이 전해졌다."] },
    { id: "chunhyang-1", persona: "chunhyang", title: "편지 한 장", description: "연인에게 소식을 보낸다.", category: "romance", tags: ["relationship"], choices: [{ text: "정성껏 답장", effects: { happiness: 1, reputation: 1, money: -1 }, personaWeight: 2 }, { text: "짧게 답장", effects: { happiness: 1, growth: 1 }, personaWeight: 0 }], stories: ["긴 편지가 마음을 녹였다.", "짧아도 연결은 이어졌다."] },
    { id: "chunhyang-2", persona: "chunhyang", title: "약속의 날", description: "약속과 일정이 겹쳤다.", category: "romance", tags: ["choice"], choices: [{ text: "약속을 지킨다", effects: { happiness: 2, money: -1 }, personaWeight: 2 }, { text: "일정을 우선", effects: { money: 1, reputation: 1 }, personaWeight: 0 }], stories: ["약속이 오래 기억되었다.", "성과는 있었지만 아쉬웠다."] },
    { id: "chunhyang-3", persona: "chunhyang", title: "소문의 검", description: "근거 없는 소문이 돈다.", category: "community", tags: ["crisis"], choices: [{ text: "당당히 해명", effects: { reputation: 2, happiness: -1 }, personaWeight: 2 }, { text: "침묵한다", effects: { growth: 1, happiness: -1 }, personaWeight: 0 }], stories: ["해명이 명예를 지켰다.", "조용히 넘겼지만 찝찝했다."] },
    { id: "heungbu-1", persona: "heungbu", title: "박씨 한 톨", description: "작은 선행을 할 기회.", category: "luck", tags: ["choice"], choices: [{ text: "선뜻 돕는다", effects: { happiness: 1, reputation: 1, money: -1 }, personaWeight: 2 }, { text: "다음에 하자", effects: { money: 1, happiness: -1 }, personaWeight: 0 }], stories: ["선행이 마음에 씨앗이 되었다.", "기회가 지나가 마음이 시큰했다."] },
    { id: "heungbu-2", persona: "heungbu", title: "뜻밖의 선물", description: "보답이 찾아왔다.", category: "luck", tags: ["festival"], choices: [{ text: "감사히 받기", effects: { money: 2, happiness: 1 }, personaWeight: 2 }, { text: "나눠 갖기", effects: { reputation: 2, happiness: 1, money: -1 }, personaWeight: 0 }], stories: ["행운이 지갑을 채웠다.", "나눔이 웃음을 키웠다."] },
    { id: "heungbu-3", persona: "heungbu", title: "형제의 갈등", description: "욕심 많은 이웃과 충돌.", category: "community", tags: ["relationship"], choices: [{ text: "부드럽게 설득", effects: { reputation: 1, growth: 1 }, personaWeight: 2 }, { text: "맞서 싸운다", effects: { happiness: 1, reputation: -1 }, personaWeight: 0 }], stories: ["말 한마디가 풀어냈다.", "속은 시원했지만 평판이 흔들렸다."] },
    { id: "nolbu-1", persona: "nolbu", title: "욕심의 손", description: "쉬운 돈벌이 제안.", category: "money", tags: ["opportunity"], choices: [{ text: "한몫 챙긴다", effects: { money: 2, reputation: -1 }, personaWeight: 2 }, { text: "분수 지킨다", effects: { reputation: 1, growth: 1 }, personaWeight: 0 }], stories: ["지갑은 두툼해졌지만 눈총도 늘었다.", "마음은 편했지만 기회는 흘렀다."] },
    { id: "nolbu-2", persona: "nolbu", title: "박을 가르는 날", description: "큰 보상이 눈앞에.", category: "luck", tags: ["fate"], choices: [{ text: "과감히 챙긴다", effects: { money: 2, happiness: -1 }, personaWeight: 2 }, { text: "공정하게 나눈다", effects: { reputation: 2, happiness: 1, money: -1 }, personaWeight: 0 }], stories: ["재물은 늘었지만 뒷맛이 씁쓸했다.", "나눔이 관계를 지켜줬다."] },
    { id: "nolbu-3", persona: "nolbu", title: "뒤늦은 깨달음", description: "욕심이 갈등을 키웠다.", category: "mistake", tags: ["crisis"], choices: [{ text: "사과한다", effects: { reputation: 1, happiness: 1 }, personaWeight: 0 }, { text: "끝까지 우긴다", effects: { reputation: -2, money: 1 }, personaWeight: 2 }], stories: ["사과가 갈등을 누그러뜨렸다.", "승자는 있었지만 친구는 없었다."] },
    { id: "don-quixote-1", persona: "don-quixote", title: "풍차 돌진", description: "위험한 도전이 보인다.", category: "growth", tags: ["fate"], choices: [{ text: "도전한다", effects: { growth: 2, health: -1 }, personaWeight: 2 }, { text: "현실을 택함", effects: { health: 1, money: 1 }, personaWeight: 0 }], stories: ["몸은 힘들었지만 꿈은 커졌다.", "안전한 선택에 마음이 차분했다."] },
    { id: "don-quixote-2", persona: "don-quixote", title: "이상과 현실", description: "불가능한 계획 제안.", category: "work", tags: ["choice"], choices: [{ text: "이상에 베팅", effects: { growth: 1, reputation: 1, money: -1 }, personaWeight: 2 }, { text: "현실적 수정", effects: { growth: 1, money: 1 }, personaWeight: 0 }], stories: ["큰 꿈이 부담도 함께 가져왔다.", "현실적인 타협이 프로젝트를 살렸다."] },
    { id: "don-quixote-3", persona: "don-quixote", title: "모험의 후폭풍", description: "도전의 여파가 온다.", category: "health", tags: ["crisis"], choices: [{ text: "버티며 끝냄", effects: { health: -1, reputation: 1, growth: 1 }, personaWeight: 2 }, { text: "잠시 쉬기", effects: { health: 2, happiness: 1 }, personaWeight: 0 }], stories: ["끝까지 가는 의지가 남았다.", "쉬어가며 힘이 돌아왔다."] },
    { id: "anne-1", persona: "anne", title: "초록 지붕 상상", description: "상상력을 살릴 시간.", category: "hobby", tags: ["daily"], choices: [{ text: "글을 쓴다", effects: { growth: 1, happiness: 1 }, personaWeight: 2 }, { text: "친구와 나눔", effects: { happiness: 1, reputation: 1 }, personaWeight: 0 }], stories: ["짧은 글이 마음을 달랬다.", "수다 속에서 이야기가 자랐다."] },
    { id: "anne-2", persona: "anne", title: "말맛의 승부", description: "발표 기회가 온다.", category: "study", tags: ["festival"], choices: [{ text: "상상 가득 발표", effects: { reputation: 1, happiness: 1 }, personaWeight: 2 }, { text: "간결하게 발표", effects: { growth: 1 }, personaWeight: 0 }], stories: ["박수와 웃음이 함께 터졌다.", "깔끔한 발표로 신뢰를 얻었다."] },
    { id: "anne-3", persona: "anne", title: "실수도 이야기", description: "작은 실수를 했다.", category: "mistake", tags: ["choice"], choices: [{ text: "유머로 넘김", effects: { happiness: 1, reputation: 1 }, personaWeight: 2 }, { text: "조용히 수습", effects: { growth: 1, reputation: 1 }, personaWeight: 0 }], stories: ["웃음이 분위기를 녹였다.", "차분한 수습으로 신뢰를 지켰다."] },
    { id: "sherlock-1", persona: "sherlock", title: "사라진 물건", description: "분실 사건이 생겼다.", category: "growth", tags: ["choice"], choices: [{ text: "추리로 해결", effects: { growth: 1, reputation: 1 }, personaWeight: 2 }, { text: "주변에 질문", effects: { reputation: 1, happiness: 1 }, personaWeight: 0 }], stories: ["단서가 맞아 떨어졌다.", "도움으로 문제를 풀었다."] },
    { id: "sherlock-2", persona: "sherlock", title: "사건의 패턴", description: "반복되는 문제가 보인다.", category: "work", tags: ["daily"], choices: [{ text: "패턴 분석", effects: { growth: 2, happiness: -1 }, personaWeight: 2 }, { text: "즉시 대응", effects: { reputation: 1, health: -1 }, personaWeight: 0 }], stories: ["원인을 찾아 장기 해결했다.", "빠른 대응으로 위기를 막았다."] },
    { id: "sherlock-3", persona: "sherlock", title: "의심과 신뢰", description: "동료가 의심스럽다.", category: "friend", tags: ["relationship"], choices: [{ text: "증거 확인", effects: { growth: 1, reputation: 1 }, personaWeight: 2 }, { text: "신뢰 선택", effects: { happiness: 1, reputation: 1 }, personaWeight: 0 }], stories: ["근거로 모두를 납득시켰다.", "신뢰가 관계를 지켰다."] },
    { id: "harry-1", persona: "harry", title: "동아리의 리더", description: "새 모임을 꾸린다.", category: "friend", tags: ["festival"], choices: [{ text: "리더로 나섬", effects: { reputation: 2, growth: 1, happiness: -1 }, personaWeight: 2 }, { text: "조용히 참여", effects: { happiness: 1, growth: 1 }, personaWeight: 0 }], stories: ["책임이 늘었지만 동료가 생겼다.", "가볍게 즐기며 배움을 얻었다."] }
  ]);

  register([
    { id: "harry-2", persona: "harry", title: "마법 같은 위기", description: "갑작스러운 문제와 맞닥뜨렸다.", category: "health", tags: ["crisis"], choices: [{ text: "맞서 싸운다", effects: { health: -1, reputation: 1, growth: 1 }, personaWeight: 2 }, { text: "도움을 요청", effects: { happiness: 1, reputation: 1 }, personaWeight: 0 }], stories: ["용기가 위기를 막았다.", "협력으로 위험을 넘겼다."] },
    { id: "harry-3", persona: "harry", title: "번개 흉터의 기억", description: "과거가 떠올랐다.", category: "growth", tags: ["fate"], choices: [{ text: "의미를 되새김", effects: { growth: 1, happiness: 1 }, personaWeight: 2 }, { text: "일상으로 돌림", effects: { happiness: 1, health: 1 }, personaWeight: 0 }], stories: ["경험이 힘이 되었다.", "현재의 평온을 지켰다."] },
    { id: "hermione-1", persona: "hermione", title: "시험 일정표", description: "공부 계획을 세운다.", category: "study", tags: ["daily"], choices: [{ text: "꼼꼼히 계획", effects: { growth: 2, happiness: -1 }, personaWeight: 2 }, { text: "유연하게 조정", effects: { growth: 1, happiness: 1 }, personaWeight: 0 }], stories: ["계획이 실력을 끌어올렸다.", "여유 덕에 꾸준했다."] },
    { id: "hermione-2", persona: "hermione", title: "도서관의 밤", description: "밤샘 공부를 고민한다.", category: "study", tags: ["choice"], choices: [{ text: "밤샘한다", effects: { growth: 2, health: -1 }, personaWeight: 2 }, { text: "일찍 쉰다", effects: { health: 2, growth: 1 }, personaWeight: 0 }], stories: ["지식은 늘었지만 피곤했다.", "컨디션을 지켜 배웠다."] },
    { id: "hermione-3", persona: "hermione", title: "규칙과 정의", description: "규칙을 어길지 고민한다.", category: "community", tags: ["fate"], choices: [{ text: "원칙을 지킨다", effects: { reputation: 1, growth: 1 }, personaWeight: 2 }, { text: "상황을 이해", effects: { happiness: 1, reputation: 1 }, personaWeight: 0 }], stories: ["원칙이 신뢰를 만들었다.", "이해가 관계를 살렸다."] },
    { id: "frodo-1", persona: "frodo", title: "무거운 짐", description: "책임이 갑자기 커졌다.", category: "growth", tags: ["choice"], choices: [{ text: "끝까지 든다", effects: { growth: 1, reputation: 1, health: -1 }, personaWeight: 2 }, { text: "나누어 든다", effects: { happiness: 1, health: 1 }, personaWeight: 0 }], stories: ["묵직하지만 성취감이 남았다.", "동행이 부담을 덜어줬다."] },
    { id: "frodo-2", persona: "frodo", title: "유혹의 반지", description: "달콤한 제안이 왔다.", category: "money", tags: ["fate"], choices: [{ text: "단호히 거절", effects: { reputation: 1, growth: 1 }, personaWeight: 2 }, { text: "잠깐 흔들림", effects: { money: 1, happiness: -1 }, personaWeight: 0 }], stories: ["원칙을 지켜 신뢰가 쌓였다.", "작은 이득이 남았지만 마음이 흔들렸다."] },
    { id: "frodo-3", persona: "frodo", title: "동행의 힘", description: "도움을 받을지 고민.", category: "friend", tags: ["relationship"], choices: [{ text: "도움을 받는다", effects: { happiness: 1, reputation: 1 }, personaWeight: 2 }, { text: "혼자 간다", effects: { growth: 1, happiness: -1 }, personaWeight: 0 }], stories: ["동료 덕분에 길이 쉬워졌다.", "고독했지만 마음은 단단했다."] },
    { id: "aragorn-1", persona: "aragorn", title: "왕의 책임", description: "리더 역할 제안.", category: "work", tags: ["opportunity"], choices: [{ text: "수락한다", effects: { reputation: 2, growth: 1, happiness: -1 }, personaWeight: 2 }, { text: "뒤에서 돕는다", effects: { reputation: 1, happiness: 1 }, personaWeight: 0 }], stories: ["책임이 늘었지만 영향력이 생겼다.", "부담은 덜고 기여했다."] },
    { id: "aragorn-2", persona: "aragorn", title: "검의 전수", description: "경험을 나눌 기회.", category: "growth", tags: ["daily"], choices: [{ text: "훈련 진행", effects: { growth: 1, reputation: 1 }, personaWeight: 2 }, { text: "기록으로 남김", effects: { growth: 1, happiness: 1 }, personaWeight: 0 }], stories: ["가르침이 신뢰를 높였다.", "기록이 오래 남았다."] },
    { id: "aragorn-3", persona: "aragorn", title: "길 잃은 동료", description: "동료가 방황한다.", category: "friend", tags: ["relationship"], choices: [{ text: "직접 나선다", effects: { reputation: 1, health: -1 }, personaWeight: 2 }, { text: "조언을 전한다", effects: { growth: 1, happiness: 1 }, personaWeight: 0 }], stories: ["행동으로 길을 열었다.", "말 한마디가 방향을 잡았다."] },
    { id: "alice-1", persona: "alice", title: "이상한 문", description: "새로운 문이 열린다.", category: "luck", tags: ["fate"], choices: [{ text: "문을 연다", effects: { growth: 1, happiness: 1 }, personaWeight: 2 }, { text: "안전하게 둔다", effects: { health: 1 }, personaWeight: 0 }], stories: ["새 경험이 펼쳐졌다.", "안정적인 하루를 지켰다."] },
    { id: "alice-2", persona: "alice", title: "티파티 초대", description: "엉뚱한 모임에 초대.", category: "friend", tags: ["festival"], choices: [{ text: "즐긴다", effects: { happiness: 2 }, personaWeight: 2 }, { text: "잠깐 들른다", effects: { happiness: 1, growth: 1 }, personaWeight: 0 }], stories: ["웃음으로 하루가 채워졌다.", "가볍게 다녀오며 균형을 지켰다."] },
    { id: "alice-3", persona: "alice", title: "규칙이 뒤집힌 날", description: "평소와 다른 규칙.", category: "mistake", tags: ["choice"], choices: [{ text: "새 규칙 적응", effects: { growth: 1, reputation: 1 }, personaWeight: 2 }, { text: "원래대로 고집", effects: { happiness: -1, reputation: 1 }, personaWeight: 0 }], stories: ["유연함이 기회를 만들었다.", "원칙은 지켰지만 답답했다."] },
    { id: "dorothy-1", persona: "dorothy", title: "집으로 가는 길", description: "가족과 일정이 겹친다.", category: "family", tags: ["choice"], choices: [{ text: "가족을 우선", effects: { happiness: 2, money: -1 }, personaWeight: 2 }, { text: "일정을 우선", effects: { money: 1, growth: 1 }, personaWeight: 0 }], stories: ["집이 가장 큰 힘이 됐다.", "성과는 있었지만 마음이 바빴다."] },
    { id: "dorothy-2", persona: "dorothy", title: "빨간 구두", description: "작은 사치가 눈에 띈다.", category: "hobby", tags: ["festival"], choices: [{ text: "즐긴다", effects: { happiness: 2, money: -1 }, personaWeight: 2 }, { text: "참는다", effects: { money: 1, growth: 1 }, personaWeight: 0 }], stories: ["작은 사치가 큰 행복이 됐다.", "절제가 마음을 단단하게 했다."] },
    { id: "dorothy-3", persona: "dorothy", title: "길 위의 동료", description: "새 동행이 생겼다.", category: "friend", tags: ["relationship"], choices: [{ text: "함께 간다", effects: { happiness: 1, reputation: 1 }, personaWeight: 2 }, { text: "혼자 간다", effects: { growth: 1, health: 1 }, personaWeight: 0 }], stories: ["동행이 길을 가볍게 했다.", "혼자서도 씩씩했다."] },
    { id: "little-prince-1", persona: "little-prince", title: "장미를 돌보는 밤", description: "소중한 것을 챙길 시간.", category: "romance", tags: ["relationship"], choices: [{ text: "정성껏 챙긴다", effects: { happiness: 1, reputation: 1, money: -1 }, personaWeight: 2 }, { text: "일정을 우선", effects: { money: 1, growth: 1 }, personaWeight: 0 }], stories: ["소중함을 지켜 마음이 따뜻했다.", "성과는 있었지만 아쉬웠다."] },
    { id: "little-prince-2", persona: "little-prince", title: "여우의 약속", description: "약속을 지킬지 고민.", category: "friend", tags: ["choice"], choices: [{ text: "약속 지킴", effects: { reputation: 1, happiness: 1 }, personaWeight: 2 }, { text: "미룬다", effects: { growth: 1, happiness: -1 }, personaWeight: 0 }], stories: ["약속이 신뢰를 만들었다.", "미룬 마음이 찝찝했다."] },
    { id: "little-prince-3", persona: "little-prince", title: "작은 별 여행", description: "새로운 경험이 온다.", category: "growth", tags: ["fate"], choices: [{ text: "여행한다", effects: { growth: 1, happiness: 1 }, personaWeight: 2 }, { text: "머문다", effects: { health: 1, reputation: 1 }, personaWeight: 0 }], stories: ["짧은 여행이 생각을 넓혔다.", "머무름이 안정감을 줬다."] },
    { id: "peter-pan-1", persona: "peter-pan", title: "네버랜드 초대", description: "놀러갈 기회가 생겼다.", category: "hobby", tags: ["festival"], choices: [{ text: "바로 간다", effects: { happiness: 2, money: -1 }, personaWeight: 2 }, { text: "다음에 가자", effects: { money: 1, growth: 1 }, personaWeight: 0 }], stories: ["아이 같은 웃음이 터졌다.", "현실을 챙기며 여운을 남겼다."] },
    { id: "peter-pan-2", persona: "peter-pan", title: "그림자 찾기", description: "잃어버린 것이 있다.", category: "growth", tags: ["choice"], choices: [{ text: "끝까지 찾는다", effects: { growth: 1, happiness: 1, health: -1 }, personaWeight: 2 }, { text: "새로 시작", effects: { happiness: 1, reputation: 1 }, personaWeight: 0 }], stories: ["찾아낸 순간이 값졌다.", "미련을 내려놓고 가벼워졌다."] },
    { id: "peter-pan-3", persona: "peter-pan", title: "어른 흉내", description: "어른답게 행동해야 한다.", category: "growth", tags: ["daily"], choices: [{ text: "어른 역할", effects: { reputation: 1, growth: 1, happiness: -1 }, personaWeight: 2 }, { text: "즐겁게 넘김", effects: { happiness: 2, reputation: -1 }, personaWeight: 0 }], stories: ["책임이 늘었지만 신뢰를 얻었다.", "가벼움이 웃음을 만들었다."] },
    { id: "wendy-1", persona: "wendy", title: "이야기 시간", description: "가족에게 이야기를 들려준다.", category: "family", tags: ["relationship"], choices: [{ text: "정성껏 들려준다", effects: { happiness: 2 }, personaWeight: 2 }, { text: "짧게 마무리", effects: { growth: 1, happiness: 1 }, personaWeight: 0 }], stories: ["이야기가 웃음을 만들었다.", "짧지만 따뜻한 시간이었다."] },
    { id: "wendy-2", persona: "wendy", title: "동생 돌보기", description: "부탁을 받았다.", category: "family", tags: ["choice"], choices: [{ text: "기꺼이 맡는다", effects: { reputation: 1, happiness: 1, health: -1 }, personaWeight: 2 }, { text: "일정을 조정", effects: { growth: 1, happiness: 1 }, personaWeight: 0 }], stories: ["책임감이 신뢰를 키웠다.", "조율로 균형을 찾았다."] }
  ]);

  register([
    { id: "wendy-3", persona: "wendy", title: "창문가의 약속", description: "집 안을 정리할 시간이 생겼다.", category: "family", tags: ["daily"], choices: [{ text: "함께 정리한다", effects: { happiness: 1, reputation: 1 }, personaWeight: 2 }, { text: "혼자 정리한다", effects: { growth: 1, health: 1 }, personaWeight: 0 }], stories: ["손을 보태며 집 안 공기가 환해졌다.", "차분히 정리하며 마음도 정돈됐다."] },
    { id: "red-hood-1", persona: "red-hood", title: "숲길의 갈림길", description: "지름길과 큰길 중 하나를 택해야 한다.", category: "health", tags: ["choice"], choices: [{ text: "큰길로 간다", effects: { health: 1, reputation: 1 }, personaWeight: 2 }, { text: "지름길로 간다", effects: { growth: 1, happiness: 1, health: -1 }, personaWeight: 0 }], stories: ["안전한 길이 하루를 지켜줬다.", "빨랐지만 마음이 조금 긴장됐다."] },
    { id: "red-hood-2", persona: "red-hood", title: "낯선 대화", description: "길에서 모르는 이가 말을 건다.", category: "community", tags: ["relationship"], choices: [{ text: "대화를 피한다", effects: { health: 1, reputation: 1 }, personaWeight: 2 }, { text: "대화를 이어간다", effects: { happiness: 1, growth: 1 }, personaWeight: 0 }], stories: ["조심스러운 선택이 평온을 지켰다.", "이야기를 나누며 배움이 있었다."] },
    { id: "red-hood-3", persona: "red-hood", title: "할머니 집 선물", description: "선물을 어떻게 전할지 고민한다.", category: "family", tags: ["relationship"], choices: [{ text: "직접 방문한다", effects: { happiness: 2, money: -1 }, personaWeight: 2 }, { text: "선물만 보낸다", effects: { money: 1, reputation: 1 }, personaWeight: 0 }], stories: ["따뜻한 방문이 웃음을 남겼다.", "실용적이었지만 아쉬움이 남았다."] },
    { id: "cinderella-1", persona: "cinderella", title: "무도회 초대", description: "화려한 무도회에 초대받았다.", category: "romance", tags: ["festival"], choices: [{ text: "무도회 참석", effects: { happiness: 2, reputation: 1, money: -1 }, personaWeight: 2 }, { text: "집안 정리", effects: { growth: 1, money: 1 }, personaWeight: 0 }], stories: ["빛나는 밤이 기억에 남았다.", "조용한 하루가 안정감을 줬다."] },
    { id: "cinderella-2", persona: "cinderella", title: "자정의 종", description: "약속한 시간을 지킬지 망설인다.", category: "romance", tags: ["fate"], choices: [{ text: "약속 지키고 돌아온다", effects: { reputation: 1, happiness: 1 }, personaWeight: 2 }, { text: "조금 더 머문다", effects: { happiness: 2, reputation: -1 }, personaWeight: 0 }], stories: ["약속이 신뢰를 지켰다.", "즐거웠지만 뒷맛이 남았다."] },
    { id: "cinderella-3", persona: "cinderella", title: "유리 구두", description: "자신의 흔적을 드러낼지 고민한다.", category: "luck", tags: ["choice"], choices: [{ text: "당당히 내세운다", effects: { reputation: 2 }, personaWeight: 2 }, { text: "조용히 숨긴다", effects: { growth: 1, happiness: 1 }, personaWeight: 0 }], stories: ["용기가 관계를 열었다.", "조용한 선택이 마음을 지켰다."] },
    { id: "rapunzel-1", persona: "rapunzel", title: "창밖의 노래", description: "혼자만의 시간을 어떻게 쓸지 결정한다.", category: "hobby", tags: ["daily"], choices: [{ text: "노래 연습", effects: { growth: 1, happiness: 1 }, personaWeight: 2 }, { text: "휴식", effects: { health: 2 }, personaWeight: 0 }], stories: ["노래가 마음의 날개가 됐다.", "쉬어가며 힘이 돌아왔다."] },
    { id: "rapunzel-2", persona: "rapunzel", title: "바깥 세상 초대", description: "문 밖의 제안이 찾아왔다.", category: "growth", tags: ["choice"], choices: [{ text: "세상으로 나간다", effects: { growth: 2, health: -1 }, personaWeight: 2 }, { text: "안전을 택한다", effects: { health: 1, money: 1 }, personaWeight: 0 }], stories: ["새로운 세상이 시야를 넓혔다.", "안정이 오늘을 지켜줬다."] },
    { id: "aladdin-1", persona: "aladdin", title: "램프의 선택", description: "뜻밖의 행운이 찾아왔다.", category: "luck", tags: ["fate"], choices: [{ text: "큰 꿈을 빈다", effects: { money: 2, happiness: 1, reputation: -1 }, personaWeight: 2 }, { text: "작은 소원을 빈다", effects: { happiness: 1, growth: 1 }, personaWeight: 0 }], stories: ["대담한 소원이 큰 파도를 일으켰다.", "소박한 바람이 마음을 채웠다."] },
    { id: "aladdin-2", persona: "aladdin", title: "시장 협상", description: "거래를 어떻게 마무리할지 고민한다.", category: "money", tags: ["choice"], choices: [{ text: "재치 있게 협상", effects: { money: 1, reputation: 1 }, personaWeight: 2 }, { text: "정직하게 거래", effects: { reputation: 1, growth: 1 }, personaWeight: 0 }], stories: ["재치가 이득을 만들었다.", "정직함이 신뢰를 남겼다."] },
    { id: "mulan-1", persona: "mulan", title: "훈련장의 선택", description: "훈련 방식에 대한 선택이 필요하다.", category: "health", tags: ["choice"], choices: [{ text: "혹독하게 훈련", effects: { growth: 2, health: -1 }, personaWeight: 2 }, { text: "균형 있게 훈련", effects: { health: 1, growth: 1 }, personaWeight: 0 }], stories: ["성장은 컸지만 몸은 무거웠다.", "균형이 꾸준함을 만들었다."] },
    { id: "mulan-2", persona: "mulan", title: "정체의 고백", description: "진실을 밝힐지 망설인다.", category: "community", tags: ["relationship"], choices: [{ text: "당당히 밝힌다", effects: { reputation: 2, happiness: -1 }, personaWeight: 2 }, { text: "조용히 넘긴다", effects: { reputation: 1, happiness: 1 }, personaWeight: 0 }], stories: ["용기가 명예를 지켰다.", "조용히 넘어가며 마음을 달랬다."] },
    { id: "robin-hood-1", persona: "robin-hood", title: "나눔의 결심", description: "불공정한 상황을 봤다.", category: "community", tags: ["opportunity"], choices: [{ text: "나눔을 실행", effects: { reputation: 2, money: -1 }, personaWeight: 2 }, { text: "합법적 모금", effects: { growth: 1, reputation: 1 }, personaWeight: 0 }], stories: ["베풂이 동네의 신뢰를 얻었다.", "절차는 느려도 마음이 편했다."] },
    { id: "robin-hood-2", persona: "robin-hood", title: "의적 작전", description: "빠른 행동과 준비 사이에서 고민한다.", category: "growth", tags: ["choice"], choices: [{ text: "기습 실행", effects: { growth: 1, reputation: 1, health: -1 }, personaWeight: 2 }, { text: "정보를 수집", effects: { growth: 1, health: 1 }, personaWeight: 0 }], stories: ["속도는 승산이었지만 몸이 고됐다.", "차분한 준비가 안전을 지켰다."] },
    { id: "elizabeth-bennet-1", persona: "elizabeth-bennet", title: "첫인상의 말", description: "마음을 표현할 기회가 왔다.", category: "romance", tags: ["choice"], choices: [{ text: "솔직하게 말한다", effects: { reputation: 1, happiness: 1 }, personaWeight: 2 }, { text: "예의를 지킨다", effects: { reputation: 1, growth: 1 }, personaWeight: 0 }], stories: ["솔직함이 관계를 움직였다.", "품격이 신뢰를 남겼다."] },
    { id: "elizabeth-bennet-2", persona: "elizabeth-bennet", title: "편견의 균열", description: "상대의 다른 면을 보았다.", category: "romance", tags: ["relationship"], choices: [{ text: "마음을 연다", effects: { happiness: 1, growth: 1 }, personaWeight: 2 }, { text: "거리를 유지", effects: { health: 1, reputation: 1 }, personaWeight: 0 }], stories: ["이해가 깊어졌다.", "안전한 거리감이 마음을 지켰다."] },
    { id: "jane-eyre-1", persona: "jane-eyre", title: "독립의 걸음", description: "스스로의 길을 정해야 한다.", category: "growth", tags: ["choice"], choices: [{ text: "스스로 길을 걷는다", effects: { growth: 2, money: -1 }, personaWeight: 2 }, { text: "안정을 택한다", effects: { money: 1, health: 1 }, personaWeight: 0 }], stories: ["독립이 자존감을 키웠다.", "안정이 숨을 돌리게 했다."] },
    { id: "jane-eyre-2", persona: "jane-eyre", title: "정직의 밤", description: "진실을 말할지 고민한다.", category: "community", tags: ["relationship"], choices: [{ text: "진실을 말한다", effects: { reputation: 2, happiness: -1 }, personaWeight: 2 }, { text: "침묵한다", effects: { happiness: 1, reputation: -1 }, personaWeight: 0 }], stories: ["정직이 신뢰를 얻었다.", "조용히 넘겼지만 마음이 무거웠다."] },
    { id: "gatsby-1", persona: "gatsby", title: "화려한 파티", description: "모두를 초대할지 고민한다.", category: "money", tags: ["festival"], choices: [{ text: "파티를 연다", effects: { reputation: 2, money: -2, happiness: 1 }, personaWeight: 2 }, { text: "소박하게 모인다", effects: { happiness: 1, money: -1 }, personaWeight: 0 }], stories: ["화려함이 사람을 모았다.", "조용한 모임이 마음을 다독였다."] },
    { id: "gatsby-2", persona: "gatsby", title: "꿈의 투자", description: "큰 기회가 눈앞에 있다.", category: "money", tags: ["opportunity"], choices: [{ text: "큰 베팅", effects: { money: 2, growth: 1, health: -1 }, personaWeight: 2 }, { text: "현실적 조정", effects: { money: 1, reputation: 1 }, personaWeight: 0 }], stories: ["도전이 크게 빛났다.", "안정적인 수익이 남았다."] },
    { id: "huck-finn-1", persona: "huck-finn", title: "강 위의 모험", description: "모험과 안전 사이에서 고민한다.", category: "hobby", tags: ["choice"], choices: [{ text: "모험을 택한다", effects: { happiness: 2, growth: 1, health: -1 }, personaWeight: 2 }, { text: "안전한 길", effects: { health: 1, reputation: 1 }, personaWeight: 0 }], stories: ["자유가 마음을 뛰게 했다.", "안전이 하루를 지켜줬다."] },
    { id: "huck-finn-2", persona: "huck-finn", title: "양심의 선택", description: "규칙과 마음이 갈린다.", category: "community", tags: ["relationship"], choices: [{ text: "마음을 따른다", effects: { reputation: 1, happiness: 1 }, personaWeight: 2 }, { text: "규칙을 지킨다", effects: { growth: 1, reputation: 1 }, personaWeight: 0 }], stories: ["양심이 길을 만들었다.", "원칙이 신뢰를 지켰다."] },
    { id: "tom-sawyer-1", persona: "tom-sawyer", title: "울타리 칠하기", description: "귀찮은 일을 해결해야 한다.", category: "work", tags: ["choice"], choices: [{ text: "재치로 부탁", effects: { reputation: 1, happiness: 1, money: 1 }, personaWeight: 2 }, { text: "직접 끝낸다", effects: { growth: 1, health: -1 }, personaWeight: 0 }], stories: ["재치가 일을 가볍게 만들었다.", "스스로 끝내며 뿌듯했다."] },
    { id: "tom-sawyer-2", persona: "tom-sawyer", title: "보물지도", description: "숨겨진 지도가 나타났다.", category: "luck", tags: ["fate"], choices: [{ text: "보물을 찾는다", effects: { money: 1, growth: 1, health: -1 }, personaWeight: 2 }, { text: "비밀로 남긴다", effects: { happiness: 1, reputation: 1 }, personaWeight: 0 }], stories: ["탐험이 손에 땀을 쥐게 했다.", "비밀을 지키며 평온했다."] },
    { id: "captain-nemo-1", persona: "captain-nemo", title: "심해 탐사", description: "깊은 바다로 나갈 기회.", category: "growth", tags: ["choice"], choices: [{ text: "탐사에 나선다", effects: { growth: 2, health: -1 }, personaWeight: 2 }, { text: "기록을 남긴다", effects: { growth: 1, health: 1 }, personaWeight: 0 }], stories: ["새 지식이 깊이를 더했다.", "기록이 안전을 지켰다."] },
    { id: "captain-nemo-2", persona: "captain-nemo", title: "고립의 선택", description: "혼자 집중할지 고민한다.", category: "community", tags: ["relationship"], choices: [{ text: "혼자 집중", effects: { growth: 1, happiness: -1 }, personaWeight: 2 }, { text: "교류 시도", effects: { happiness: 1, reputation: 1 }, personaWeight: 0 }], stories: ["집중은 늘었지만 고독이 남았다.", "교류가 마음을 풀어줬다."] },
    { id: "odysseus-1", persona: "odysseus", title: "유혹의 노래", description: "달콤한 유혹이 들려온다.", category: "growth", tags: ["fate"], choices: [{ text: "규칙을 지킨다", effects: { growth: 1, health: 1 }, personaWeight: 2 }, { text: "유혹을 살핀다", effects: { happiness: 1, reputation: -1 }, personaWeight: 0 }], stories: ["절제가 길을 지켜줬다.", "호기심이 마음을 흔들었다."] },
    { id: "odysseus-2", persona: "odysseus", title: "집으로 돌아가는 길", description: "돌아갈 길과 새 길 사이.", category: "family", tags: ["choice"], choices: [{ text: "집으로 돌아간다", effects: { happiness: 1, reputation: 1 }, personaWeight: 2 }, { text: "다른 길로 간다", effects: { growth: 1, money: 1 }, personaWeight: 0 }], stories: ["가족의 품이 힘이 됐다.", "새 길이 성장을 불렀다."] },
    { id: "conan-1", persona: "conan", title: "사건 현장", description: "단서가 흩어져 있다.", category: "growth", tags: ["choice"], choices: [{ text: "단서를 추적", effects: { growth: 2, reputation: 1, health: -1 }, personaWeight: 2 }, { text: "협력 요청", effects: { reputation: 1, happiness: 1 }, personaWeight: 0 }], stories: ["집중이 사건을 풀었다.", "협력이 해결을 앞당겼다."] },
    { id: "conan-2", persona: "conan", title: "범인의 심리", description: "머릿속에서 퍼즐을 맞춘다.", category: "study", tags: ["daily"], choices: [{ text: "집중 분석", effects: { growth: 2, happiness: -1 }, personaWeight: 2 }, { text: "직감 추리", effects: { growth: 1, happiness: 1 }, personaWeight: 0 }], stories: ["분석이 답을 이끌었다.", "직감이 의외의 길을 열었다."] },
    { id: "luffy-1", persona: "luffy", title: "동료 모집", description: "함께할 사람을 만났다.", category: "friend", tags: ["relationship"], choices: [{ text: "믿고 영입", effects: { reputation: 1, happiness: 2 }, personaWeight: 2 }, { text: "검증 후 결정", effects: { growth: 1, reputation: 1 }, personaWeight: 0 }], stories: ["믿음이 팀을 키웠다.", "차분한 검증이 신뢰를 만들었다."] },
    { id: "luffy-2", persona: "luffy", title: "거대한 바다", description: "출항을 결정해야 한다.", category: "hobby", tags: ["festival"], choices: [{ text: "모험 출항", effects: { happiness: 2, growth: 1, health: -1 }, personaWeight: 2 }, { text: "준비 먼저", effects: { growth: 1, health: 1 }, personaWeight: 0 }], stories: ["모험이 가슴을 뛰게 했다.", "준비가 안전을 보장했다."] },
    { id: "naruto-1", persona: "naruto", title: "끝까지 도전", description: "포기하고 싶은 순간이 왔다.", category: "growth", tags: ["choice"], choices: [{ text: "끝까지 도전", effects: { growth: 2, reputation: 1, health: -1 }, personaWeight: 2 }, { text: "지지 요청", effects: { reputation: 1, happiness: 1 }, personaWeight: 0 }], stories: ["뚝심이 주변을 움직였다.", "도움이 마음을 지켜줬다."] },
    { id: "naruto-2", persona: "naruto", title: "우정의 약속", description: "친구와 약속이 겹쳤다.", category: "friend", tags: ["relationship"], choices: [{ text: "약속을 지킨다", effects: { happiness: 1, reputation: 1 }, personaWeight: 2 }, { text: "훈련을 우선", effects: { growth: 1, health: 1 }, personaWeight: 0 }], stories: ["약속이 관계를 지켰다.", "훈련으로 실력이 쌓였다."] },
    { id: "goku-1", persona: "goku", title: "한계 수련", description: "몸을 단련할 시간이다.", category: "health", tags: ["daily"], choices: [{ text: "한계 도전", effects: { growth: 2, health: -1 }, personaWeight: 2 }, { text: "균형 훈련", effects: { health: 1, growth: 1 }, personaWeight: 0 }], stories: ["성장은 컸지만 몸이 무거웠다.", "균형이 꾸준함을 만들었다."] },
    { id: "goku-2", persona: "goku", title: "대회 참가", description: "경기에 나갈지 고민한다.", category: "growth", tags: ["festival"], choices: [{ text: "출전한다", effects: { reputation: 1, happiness: 1, health: -1 }, personaWeight: 2 }, { text: "연습을 계속", effects: { growth: 1, health: 1 }, personaWeight: 0 }], stories: ["무대가 자신감을 키웠다.", "연습이 내공을 쌓았다."] },
    { id: "eren-1", persona: "eren", title: "벽 밖의 결심", description: "새로운 길을 열 기회가 있다.", category: "growth", tags: ["choice"], choices: [{ text: "나아간다", effects: { growth: 2, health: -1 }, personaWeight: 2 }, { text: "신중히 준비", effects: { growth: 1, health: 1 }, personaWeight: 0 }], stories: ["결심이 길을 열었다.", "준비가 리스크를 줄였다."] },
    { id: "eren-2", persona: "eren", title: "자유의 대가", description: "책임을 얼마나 질지 고민한다.", category: "community", tags: ["crisis"], choices: [{ text: "책임을 감수", effects: { reputation: 1, growth: 1, happiness: -1 }, personaWeight: 2 }, { text: "공동 결정", effects: { reputation: 1, happiness: 1 }, personaWeight: 0 }], stories: ["책임이 무거웠지만 의미가 남았다.", "함께 결정해 마음이 덜했다."] },
    { id: "spiderman-1", persona: "spiderman", title: "큰 힘의 선택", description: "도움을 요청하는 사람이 있다.", category: "community", tags: ["choice"], choices: [{ text: "도움을 선택", effects: { reputation: 2, happiness: 1, money: -1 }, personaWeight: 2 }, { text: "일정을 우선", effects: { money: 1, growth: 1 }, personaWeight: 0 }], stories: ["도움이 큰 신뢰를 만들었다.", "일정은 지켰지만 마음이 바빴다."] },
    { id: "spiderman-2", persona: "spiderman", title: "비밀 유지", description: "가까운 사람에게 말할지 고민한다.", category: "friend", tags: ["relationship"], choices: [{ text: "비밀을 지킨다", effects: { reputation: 1, happiness: -1 }, personaWeight: 2 }, { text: "솔직히 말한다", effects: { happiness: 1, reputation: 1 }, personaWeight: 0 }], stories: ["책임을 지키며 외로움이 남았다.", "솔직함이 관계를 살렸다."] },
    { id: "spiderman-3", persona: "spiderman", title: "도시 순찰", description: "밤 시간을 어떻게 쓸지 선택한다.", category: "health", tags: ["daily"], choices: [{ text: "밤까지 순찰", effects: { reputation: 1, health: -1, growth: 1 }, personaWeight: 2 }, { text: "휴식한다", effects: { health: 2, happiness: 1 }, personaWeight: 0 }], stories: ["도시는 안전했지만 몸이 지쳤다.", "쉬어가며 힘을 회복했다."] },
    { id: "batman-1", persona: "batman", title: "어둠의 계획", description: "작전을 준비할 시간이다.", category: "growth", tags: ["choice"], choices: [{ text: "치밀하게 준비", effects: { growth: 2, money: -1 }, personaWeight: 2 }, { text: "즉시 출동", effects: { reputation: 1, health: -1 }, personaWeight: 0 }], stories: ["준비가 승산을 높였다.", "즉시 움직여 위기를 막았다."] },
    { id: "batman-2", persona: "batman", title: "장비 업그레이드", description: "예산을 어디에 쓸지 고민.", category: "money", tags: ["opportunity"], choices: [{ text: "장비에 투자", effects: { money: -2, reputation: 1, growth: 1 }, personaWeight: 2 }, { text: "자선에 지원", effects: { reputation: 2, happiness: 1, money: -1 }, personaWeight: 0 }], stories: ["장비가 든든해졌다.", "나눔이 도시의 신뢰를 키웠다."] },
    { id: "batman-3", persona: "batman", title: "고독과 동료", description: "혼자 할지 함께 할지 고민.", category: "friend", tags: ["relationship"], choices: [{ text: "혼자 해결", effects: { growth: 1, happiness: -1 }, personaWeight: 2 }, { text: "협력 요청", effects: { happiness: 1, reputation: 1 }, personaWeight: 0 }], stories: ["성과는 있었지만 외로웠다.", "협력이 마음을 지켜줬다."] },
    { id: "elsa-1", persona: "elsa", title: "얼음의 수련", description: "힘을 다스릴 시간이 왔다.", category: "growth", tags: ["choice"], choices: [{ text: "혼자 수련", effects: { growth: 2, happiness: -1 }, personaWeight: 2 }, { text: "도움 요청", effects: { happiness: 1, reputation: 1 }, personaWeight: 0 }], stories: ["수련이 자신감을 키웠다.", "도움이 마음을 풀어줬다."] },
    { id: "elsa-2", persona: "elsa", title: "마음의 문", description: "가까운 사람에게 마음을 열지 고민.", category: "family", tags: ["relationship"], choices: [{ text: "마음을 연다", effects: { happiness: 2, reputation: 1 }, personaWeight: 2 }, { text: "거리 두기", effects: { health: 1, growth: 1 }, personaWeight: 0 }], stories: ["따뜻한 온기가 번졌다.", "거리감이 안정감을 줬다."] },
    { id: "anna-1", persona: "anna", title: "자매의 손", description: "먼저 다가갈지 결정한다.", category: "family", tags: ["relationship"], choices: [{ text: "먼저 손 내밀기", effects: { happiness: 2, reputation: 1 }, personaWeight: 2 }, { text: "기다리기", effects: { growth: 1, happiness: 1 }, personaWeight: 0 }], stories: ["용기가 관계를 살렸다.", "기다림이 마음을 정리했다."] },
    { id: "anna-2", persona: "anna", title: "즉흥 여행", description: "갑작스러운 여행 제안.", category: "hobby", tags: ["choice"], choices: [{ text: "지금 떠난다", effects: { happiness: 2, health: -1 }, personaWeight: 2 }, { text: "계획을 세운다", effects: { growth: 1, health: 1 }, personaWeight: 0 }], stories: ["즉흥이 웃음을 만들었다.", "계획이 안전을 지켰다."] },
    { id: "momo-1", persona: "momo", title: "시간을 지키는 법", description: "바쁨과 여유 사이에서 고민.", category: "growth", tags: ["choice"], choices: [{ text: "느리게 집중", effects: { growth: 1, happiness: 1 }, personaWeight: 2 }, { text: "바삐 처리", effects: { money: 1, health: -1 }, personaWeight: 0 }], stories: ["천천히 해도 깊이가 남았다.", "빠르게 끝냈지만 숨이 찼다."] },
    { id: "momo-2", persona: "momo", title: "이야기를 듣는 아이", description: "누군가 이야기를 들려달라고 한다.", category: "friend", tags: ["relationship"], choices: [{ text: "끝까지 듣기", effects: { reputation: 1, happiness: 1 }, personaWeight: 2 }, { text: "짧게 요약", effects: { growth: 1, money: 1 }, personaWeight: 0 }], stories: ["귀 기울임이 신뢰를 만들었다.", "효율은 좋았지만 여운이 적었다."] }
  ]);

  window.GARDEN_EVENTS = events;
  window.GARDEN_EVENT_STORIES = stories;
})();
